export const initialData: Record<string, any[]> = {
  utilisateur: [],
  organisme: [],
  laboratoire: [],
  echantillon: [],
  laboriste: [],
  diplome: [],
  obtenir: [],
  processus_analyse: [],
  resultat: [],
  equipement: [],
  etalonnage: [],
  effectuer_analyse: [],
  effectuer_etalonnage: [],
  norme: [],
  comparer_norme: [],
  historique: [],
  emploie: [],
  affectation: []
};
